name: Build u-boot for RK356x Orangepi
run-name: u-boot ${{ inputs.uboot_repo }} - ${{ inputs.uboot_ref }} for RK356x
on:
  workflow_dispatch:
    inputs:
      uboot_repo:
        description: u-boot repo
        required: true
        default: orangepi-xunlong/u-boot-orangepi
        type: choice
        options:
          - orangepi-xunlong/u-boot-orangepi
      uboot_ref:
        description: u-boot ref
        required: true
        default: 752ac3f2fdcfe9427ca8868d95025aacd48fc00b
        type: choice
        options:
          - 752ac3f2fdcfe9427ca8868d95025aacd48fc00b
          - v2020.04
      rkbin_repo:
        description: rkbin repo
        required: true
        default: rockchip-linux/rkbin
        type: choice
        options:
          - rockchip-linux/rkbin
      rkbin_ref:
        description: rkbin ref
        required: true
        default: master
        type: choice
        options:
          - master

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        boards:
          [
            {
              "name": "rk3568-dg-tn3568",
              "config": "rk3568-dg-tn3568_defconfig",
              "variant": "RK3568",
            },
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc gcc-aarch64-linux-gnu python3-pyelftools confget libgnutls28-dev uuid-dev device-tree-compiler libncurses5-dev build-essential libssl-dev mtools bc dosfstools flex bison

      - name: Checkout rkbin - ${{ inputs.rkbin_repo }} - ${{ inputs.rkbin_ref }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.rkbin_repo }}
          ref: ${{ inputs.rkbin_ref }}
          path: rkbin

      - name: Checkout u-boot -  ${{ inputs.uboot_repo }} - ${{ inputs.uboot_ref }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.uboot_repo }}
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Add Coustom Dts and Defconfig
        run: |
          curl -L "https://raw.githubusercontent.com/bigmangos/u-boot-build/refs/heads/main/rk3568-dg-tn3568.dts" -o u-boot/arch/arm/dts/rk3568-dg-tn3568.dts
          curl -L "https://raw.githubusercontent.com/bigmangos/u-boot-build/refs/heads/main/rk3568-dg-tn3568_defconfig" -o u-boot/configs/rk3568-dg-tn3568_defconfig

      - name: Build u-boot - ${{ matrix.boards.config }}
        id: build
        if: ${{ hashFiles(format('u-boot/configs/{0}', matrix.boards.config)) != ''}}
        run: |
          DDRBIN=$(confget -f rkbin/RKBOOT/${{ matrix.boards.variant }}MINIALL.ini -s LOADER_OPTION FlashData)
          sed -i 's/uart baudrate=/uart baudrate=${{ matrix.boards.baudrate }}/' rkbin/tools/ddrbin_param.txt
          sed -i 's/dis_train_print=/dis_train_print=1/' rkbin/tools/ddrbin_param.txt
          SOC=$(echo "${{ matrix.boards.variant }}" | tr '[:upper:]' '[:lower:]')
          rkbin/tools/ddrbin_tool $SOC rkbin/tools/ddrbin_param.txt rkbin/$DDRBIN
          export ROCKCHIP_TPL=../rkbin/$DDRBIN
          export BL31=../rkbin/$(confget -f rkbin/RKTRUST/RK3568TRUST.ini -s BL31_OPTION PATH)
          cd u-boot
          make mrproper
          make ${{ matrix.boards.config }}
          make -Wformat-truncation= -Warray-bounds= -Wformat-overflow= -Werror=maybe-uninitialized -Werror=address CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          pwd
          tree
          tools/mkimage -l u-boot.itb
          sha256sum idbloader.img u-boot.itb u-boot-rockchip.bin $(ls u-boot-rockchip-spi.bin) > sha256sums.txt

      - name: Upload artifacts
        if: ${{ success() && steps.build.conclusion != 'skipped' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/idbloader.img
            u-boot/u-boot.itb
            u-boot/u-boot-rockchip.bin
            u-boot/u-boot-rockchip-spi.bin
            u-boot/sha256sums.txt
